
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
export const Index = {
"action-button-are-you-sure": {
	files: ["src/lib/registry/examples/action-button-are-you-sure.svelte"],
},
"action-button-default": {
	files: ["src/lib/registry/examples/action-button-default.svelte"],
},
"action-button-demo": {
	files: ["src/lib/registry/examples/action-button-demo.svelte"],
},
"action-button-error": {
	files: ["src/lib/registry/examples/action-button-error.svelte"],
},
"loading-swap-demo": {
	files: ["src/lib/registry/examples/loading-swap-demo.svelte"],
},
"loading-swap-large": {
	files: ["src/lib/registry/examples/loading-swap-large.svelte"],
},
}
