
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
export const Index = {
"hello-world-demo": {
	files: ["src/lib/registry/examples/hello-world-demo.svelte"],
},
}
