// This file is generated by Velite

import type __vc from '../velite.config.js'

type Collections = typeof __vc.collections

export type components = Collections['components']['schema']['_output']
export declare const components: components[]

export type installation = Collections['installation']['schema']['_output']
export declare const installation: installation[]
