// This file is generated by Velite

export { default as components } from './components.json' with { type: 'json' }
export { default as installation } from './installation.json' with { type: 'json' }