import fs from 'node:fs';
import path from 'node:path';
import prettier from 'prettier';
import { rimraf } from 'rimraf';
import {
	componentsJsonSchema,
	registryItemSchema,
	registrySchema,
	type Registry,
	type RegistryItemType
} from '@shadcn-svelte/registry';
import { buildRegistry } from './registry';
import { toJSONSchema } from 'zod/v4';

const prettierConfig = await prettier.resolveConfig(import.meta.url);
if (!prettierConfig) throw new Error('Failed to resolve prettier config.');

function writeFileWithDirs(
	filePath: string,
	data: string,
	options: Parameters<typeof fs.writeFileSync>[2] = {}
): void {
	// Create directory path if it doesn't exist
	const dirname = path.dirname(filePath);
	fs.mkdirSync(dirname, { recursive: true });

	// Write the file
	fs.writeFileSync(filePath, data, options);
}

export async function build(): Promise<void> {
	const registry = await buildRegistry();

	const selfReferenced = registry.filter((item) => item.registryDependencies.includes(item.name));
	const selfReferenceError = selfReferenced
		.map((item) => `Registry item '${item.name}' depends on itself`)
		.join('\n');
	if (selfReferenceError) {
		throw new Error(selfReferenceError);
	}

	// ----------------------------------------------------------------------------
	// Build `registry.json` file.
	// ----------------------------------------------------------------------------
	const result = registrySchema.parse(
		{
			$schema: './static/schema/registry.json',
			name: 'wds-shadcn-registry-svelte',
			homepage: 'https://localhost:5173',
			aliases: {
				lib: '$lib/registry/lib',
				ui: '$lib/registry/ui',
				components: './components',
				hooks: '$lib/registry/hooks',
				utils: '$lib/utils'
			},
			items: [...registry]
		} as Registry,
		// maintains the schema defined property order
		{ jitless: true }
	);

	const ITEM_TYPES: RegistryItemType[] = [
		'registry:ui',
		'registry:hook',
		'registry:component',
		'registry:lib',
		'registry:block'
	];
	const filteredItems = result.items.filter((item) => ITEM_TYPES.includes(item.type));
	const registryJsonPath = path.resolve('registry.json');

	const registryJson = JSON.stringify({ ...result, items: filteredItems }, null, '\t');
	const formatted = await prettier.format(registryJson, {
		...prettierConfig,
		filepath: registryJsonPath
	});
	fs.writeFileSync(registryJsonPath, formatted, 'utf8');

	// ----------------------------------------------------------------------------
	// Build __registry__/blocks.ts
	// ----------------------------------------------------------------------------
	rimraf.sync(path.resolve('src', '__registry__'));

	let blocksIndex = `
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
export const blocks = [
`; // Creates block index files
	for (const block of result.items) {
		if (block.type !== 'registry:block' || block.name.startsWith('chart-')) continue;

		blocksIndex += `"${block.name}",`;
	}

	blocksIndex += '\n] as const;\n';
	const blocksPath = path.resolve('src', '__registry__', 'blocks.ts');
	writeFileWithDirs(blocksPath, blocksIndex);

	// ----------------------------------------------------------------------------
	// Build __registry__/index.js.
	// ----------------------------------------------------------------------------
	let index = `
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
export const Index = {`;

	// TODO: fix later - we should either add these calendar examples to
	// the `lib/registry/examples` dir, or... do something else?
	const CALENDAR_EXAMPLES = ['02', '13', '22', '24', '29'].map((n) => `calendar-${n}`);

	// Build style index.
	for (const item of result.items) {
		if (item.type !== 'registry:example' && !CALENDAR_EXAMPLES.includes(item.name)) {
			continue;
		}

		const resolveFiles = item.files.map((file) => file.path.replace('src/', '../'));

		index += `
"${item.name}": {
	files: [${resolveFiles.map((file) => `"${file.replaceAll(path.sep, '/')}"`)}],
},`;
	}

	index += `
}
`;

	// Write style index.
	const registryPath = path.resolve('src', '__registry__', 'index.js');
	rimraf.sync(registryPath);
	writeFileWithDirs(registryPath, index);

	// ----------------------------------------------------------------------------
	// Build static/schema.json
	// ----------------------------------------------------------------------------
	const componentsJSON = toJSONSchema(componentsJsonSchema);
	writeFileWithDirs(
		path.resolve('static', 'schema.json'),
		JSON.stringify(componentsJSON, null, '\t')
	);

	// ----------------------------------------------------------------------------
	// Build static/schema/registry.json
	// ----------------------------------------------------------------------------
	const SCHEMA_DIR = path.resolve('static', 'schema');
	writeFileWithDirs(
		path.resolve(SCHEMA_DIR, 'registry.json'),
		JSON.stringify(toJSONSchema(registrySchema), null, '\t')
	);

	// ----------------------------------------------------------------------------
	// Build static/schema/registry-item.json
	// ----------------------------------------------------------------------------
	writeFileWithDirs(
		path.resolve(SCHEMA_DIR, 'registry-item.json'),
		JSON.stringify(toJSONSchema(registryItemSchema), null, '\t')
	);
}

if (process.argv.includes('build-registry')) {
	build();
}
